# Generated by Django 5.0.2 on 2024-04-06 15:33

import chat.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(verbose_name='ChatGroup UUID, generate from seed + usernames')),
                ('name', models.CharField(max_length=200, validators=[chat.validators.offensive_name])),
            ],
        ),
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('date_save', models.DateTimeField(auto_now_add=True, verbose_name='Record date')),
                ('date_pub', models.DateTimeField(validators=[chat.validators.validate_futur], verbose_name='Publication date')),
                ('body', models.CharField(max_length=512)),
                ('conv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatgroup')),
                ('respond_to', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.chatmessage', verbose_name='In response to')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatuser', verbose_name='Author')),
            ],
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='participants',
            field=models.ManyToManyField(related_name='conv', to='chat.chatuser'),
        ),
    ]
