# Generated by Django 5.0.2 on 2024-04-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='members',
            field=models.ManyToManyField(related_name='group', to='chat.chatuser'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='contact_list',
            field=models.ManyToManyField(related_name='contacts', to='chat.chatuser'),
        ),
    ]
