# Generated by Django 5.0.2 on 2024-05-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelation',
            name='status',
            field=models.CharField(choices=[('i', 'Invit'), ('b', 'Block'), ('c', 'Comrade')]),
        ),
    ]
