# Generated by Django 5.0.2 on 2024-05-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupship',
            name='last_read',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
