# Generated by Django 5.0.2 on 2024-04-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='blocked_list',
            field=models.ManyToManyField(related_name='blocked', to='chat.chatuser'),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='contact_list',
            field=models.ManyToManyField(related_name='contact', to='chat.chatuser'),
        ),
    ]
