# Generated by Django 5.0.2 on 2024-04-27 20:17

import chat.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'default_related_name': 'messages', 'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='date_pub',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='date_save',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[chat.validators.validate_futur], verbose_name='Publication date'),
        ),
    ]
