# Generated by Django 5.0.2 on 2024-04-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatgroup_members_alter_chatuser_contact_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='contact_list',
            field=models.ManyToManyField(to='chat.chatuser'),
        ),
    ]
