# Generated by Django 5.0.2 on 2024-05-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_userrelation_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRelation',
            new_name='Relation',
        ),
        migrations.AlterField(
            model_name='groupship',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'restrict'), (1, 'member'), (2, 'admin'), (3, 'owner')], default=1),
        ),
    ]
