# Generated by Django 5.0.2 on 2024-05-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_groupship_last_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupship',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Reader'), (1, 'Writer'), (2, 'Admin'), (3, 'Owner')], default=1),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='status',
            field=models.CharField(choices=[('I', 'Invit'), ('B', 'Block'), ('C', 'Comrade')]),
        ),
    ]
