# Generated by Django 5.0.2 on 2024-05-05 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_type_userrelation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupship',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupships', to='chat.chatgroup'),
        ),
        migrations.AlterField(
            model_name='groupship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupship', to='chat.chatuser'),
        ),
    ]
