# Generated by Django 5.0.2 on 2024-05-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_groupship_group_alter_groupship_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='contacts',
            field=models.ManyToManyField(related_name='+', through='chat.UserRelation', to='chat.chatuser'),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='status',
            field=models.CharField(choices=[('I', 'Invit'), ('ID', 'Invited'), ('B', 'Block'), ('BD', 'Blocked'), ('C', 'Comrade')]),
        ),
    ]
