# Generated by Django 5.0.2 on 2024-05-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_groupship_role_alter_userrelation_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatGroup',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='ChatMessage',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='ChatUser',
            new_name='User',
        ),
    ]
