# Generated by Django 5.0.2 on 2024-05-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_userrelation_relation_alter_groupship_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='status',
            field=models.CharField(choices=[('invitation', 'Invit'), ('block', 'Block'), ('contact', 'Comrade')]),
        ),
    ]
