# Generated by Django 5.0.2 on 2024-04-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatuser_buid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='buid',
            field=models.UUIDField(unique=True),
        ),
    ]
