# Generated by Django 5.0.2 on 2024-04-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatuser_buid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='contact_list',
            field=models.ManyToManyField(to='chat.chatuser'),
        ),
    ]
