# Generated by Django 5.0.2 on 2024-04-07 09:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatuser_contact_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='uuid',
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='cid',
            field=models.UUIDField(default=uuid.UUID('92f762d3-316d-4419-97d7-1d63f7e3a539'), verbose_name='ChatGroup UUID'),
        ),
    ]
