# Generated by Django 5.0.2 on 2024-04-07 09:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chatgroup_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='cid',
            field=models.UUIDField(default=uuid.UUID('50ba548b-e5ff-4e27-9fb1-0f3f52ee58a3'), verbose_name='ChatGroup UUID'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='participants',
            field=models.ManyToManyField(to='chat.chatuser'),
        ),
    ]
