# Generated by Django 5.0.2 on 2024-04-07 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_chatgroup_cid_alter_chatgroup_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='uuid',
            new_name='mid',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='cid',
            field=models.UUIDField(default=uuid.UUID('c74bbcc3-7979-40df-b780-65ab9458ced8'), verbose_name='ChatGroup UUID'),
        ),
    ]
