# Generated by Django 5.0.2 on 2024-04-07 13:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_rename_uuid_chatmessage_mid_alter_chatgroup_cid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatuser',
            old_name='buid',
            new_name='uid',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='cid',
            field=models.UUIDField(default=uuid.UUID('fe40118d-acc7-4335-aafe-3c3bde542742'), verbose_name='ChatGroup UUID'),
        ),
    ]
