# Generated by Django 5.0.2 on 2024-04-08 10:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_chatgroup_cid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatgroup',
            old_name='participants',
            new_name='members',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='cid',
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='gid',
            field=models.UUIDField(default=uuid.UUID('8da522f3-14e5-4f56-a1d8-3e4776f985ce'), unique=True, verbose_name='ChatGroup ID'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='uid',
            field=models.UUIDField(unique=True, verbose_name='User ID'),
        ),
    ]
