# Generated by Django 5.0.2 on 2024-04-08 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_rename_participants_chatgroup_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='gid',
            field=models.UUIDField(default=uuid.UUID('4eaec23d-2fbb-4aff-84b6-1091cc2fd741'), unique=True, verbose_name='ChatGroup ID'),
        ),
    ]
