# Generated by Django 5.0.2 on 2024-04-09 10:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_chatgroup_gid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='gid',
            field=models.UUIDField(default=uuid.UUID('8957dc45-c465-4a30-bd6a-fa70e1809382'), unique=True, verbose_name='ChatGroup ID'),
        ),
    ]
