version: '3.7'

services:
  django:
    container_name: ${APP_NAME}
    build:
      context: django/
      args: 
        PORT: ${APP_PORT}
    image: ${APP_NAME}_image:${VERSION}
    environment:
      APP_NAME: ${APP_NAME}
      HOST: ${APP_HOST}
      PORT: ${APP_PORT}
    volumes:
      - source_code:/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks: 
      - app_network
    restart: unless-stopped
    # depends_on:
    #   - postgres
    stdin_open: true 
    tty: true

  postgres:
    container_name: ${DB_NAME}
    build:
      context: postgres/
      args: 
        PORT: ${DB_PORT}
    image: ${DB_NAME}_image:${VERSION}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PORT: ${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: 
      - app_network
    restart: unless-stopped


volumes:
  source_code:
    name: ${APP_VOLUME} 
    driver: local
    driver_opts:
      type: none
      device: django/src/
      o: bind

  pgdata:
    name: test 
    driver: local
    driver_opts:
      type: none
      o: bind

networks:
  app_network:
    name: dev_network
    driver: bridge

