version: '3.9'

services:
  django:
    container_name: ${APP_NAME}
    build:
      context: django/
    image: ${APP_NAME}_image:${VERSION}
    environment:
      APP_NAME: ${APP_NAME}
      HOST: ${APP_HOST}
      PORT: ${APP_PORT}
      DB_USER: ${DJ_USER}
      DB_PASSWORD: ${DJ_PASSWORD}
      DB_NAME: ${DJ_DB}
      DB_HOST: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    volumes:
      - source_code:/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks: 
      - app_network
    restart: unless-stopped
    stdin_open: true 
    tty: true
    depends_on:
      - postgres

  postgres:
    container_name: ${DB_NAME}
    build:
      context: postgres/
      args: 
        PORT: ${DB_PORT}
        PGDIR: ${PGDATA}
    image: ${DB_NAME}_image:${VERSION}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
      DB_USER: ${DJ_USER}
      DB_PASSWORD: ${DJ_PASSWORD}
      DB_NAME: ${DJ_DB}
    volumes:
      - pgdata:${PGDATA}
    networks: 
      - app_network
    restart: unless-stopped


volumes:
  source_code:
    name: ${APP_VOLUME} 
    driver: local
    driver_opts:
      type: none
      device: django/src
      o: bind

  pgdata:
    name: ${DB_VOLUME}
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/goinfre/my_docker/${DB_VOLUME}_data
      o: bind

networks:
  app_network:
    name: dev_network
    driver: bridge

