version: '3.7'

services:
  django:
    container_name: ${APP_NAME}
    build:
      context: django/
      args: 
        PORT: ${APP_PORT}
    image: ${APP_NAME}_image:${VERSION}
    environment:
      APP_NAME: ${APP_NAME}
      HOST: ${APP_HOST}
      PORT: ${APP_PORT}
    volumes:
    - source_code:/app
    ports:
    - "${APP_PORT}:${APP_PORT}"
    networks: 
      - app_network
    restart: unless-stopped
    stdin_open: true 
    tty: true

volumes:
  source_code:
    name: ${APP_VOLUME} 
    driver: local
    driver_opts:
      type: none
      device: django/src/
      o: bind


networks:
  app_network:
    name: dev_network
    driver: bridge

