version: '3.7'

services:
  django:
    build: django/
    container_name: django_app
    volumes:
    - app_data:/code
    ports:
    - "8000:8000"
    networks: 
      - app_network
    restart: unless-stopped
    stdin_open: true 
    tty: true

volumes:
  app_data:
    driver: local
    name: app_data 
    driver_opts:
      type: none
      device: django/app/
      o: bind

networks:
  app_network:
    driver: bridge
    name: app_network


    # https://stackoverflow.com/questions/57591111/file-permission-in-docker-container-with-volume-mount
    # https://docs.docker.com/storage/volumes/
# https://stackoverflow.com/questions/29245216/write-in-shared-volumes-docker

