FROM jmoutous/nginx-waf-jmoutous:latest

# Copy our homemade Nginx's configuration
COPY nginx.conf /etc/nginx/nginx.conf
COPY proxy_waf.conf /etc/nginx/conf.d/default.conf
RUN mkdir -p /certs /var/www/static


# Reboot the Nginx's container in order to apply every changes
STOPSIGNAL SIGQUIT
CMD ["nginx", "-g", "daemon off;"]
