#image officiel de python, base sur alpine pour une taille minuscule
FROM python:3.12-alpine3.19

ENV PYTHONUNBUFFERED 1

COPY src/ /app
COPY conf/ /conf/
RUN pip install -r /conf/requirements.txt 

EXPOSE ${PORT}
