services:
  game:
    container_name: game
    build:
      context: apps/game/
      dockerfile: Dockerfile.dev
    image: game_image
    volumes:
      - game_volume:/app
    networks:
      - app_network
    restart: unless-stopped
    stdin_open: true 
    tty: true
    # entrypoint: ["python", "/app/manage.py", "runserver", "0.0.0.0:8000"]

volumes:
  game_volume:
    name: game_volume
    driver: local
    driver_opts:
      type: none
      device: apps/game/src
      o: bind
      