services:
  proxy:
    container_name: proxy
    depends_on:
      auth:
       condition: service_started
      chat:
       condition: service_started
      chat-redis:
       condition: service_started
    image: owasp/modsecurity-crs:4.2-nginx-alpine-202405220605
    environment:
      - TZ=${TZ}
      - SERVER_NAME=${SERVER_NAME}
    env_file:
      - conf/proxy.env
    ports:
     - "8443:8443"
     - "8080:8080"
    networks: 
      - app_network
    volumes:
      - ${PATH_TO_CERT}:/etc/nginx/conf/server.crt:ro
      - ${PATH_TO_KEY}:/etc/nginx/conf/server.key:ro
      - ./front:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/templates/conf.d/default.conf.template:ro
      - ./nginx/proxy_backend.conf:/etc/nginx/templates/includes/proxy_backend.conf.template:ro
    restart: unless-stopped

