services:
  django:
    container_name: ${APP_NAME_1}
    build:
      context: apps/game/django/
      dockerfile: Dockerfile.dev
    image: ${APP_NAME_1}_image
    env_file:
      - apps/game/app.env.example
    volumes:
      - source_code:/app
      - ./logs:/logs
    networks:
      - app_network
    restart: unless-stopped
    entrypoint: ["python", "/app/manage.py", "runserver", "0.0.0.0:${APP_PORT_1}"]

volumes:
  source_code:
    name: ${APP_VOLUME_1}_bis
    driver: local
    driver_opts:
      type: none
      device: apps/game/django/src
      o: bind
      