services:
  proxy:
    container_name: proxy-nginx
    build:
      context: server
      dockerfile: Dockerfile.nginx
    image: proxy-nginx
    ports:
     - "443:443"
     - "80:80"
    networks: 
      - app_network
      - elk_log
    volumes:
      - ./server/certs/:/certs
      - ./front:/var/www/static
      - ./nginx_logs:/var/log/nginx  # Assurez-vous que Nginx est configuré pour écrire les logs ici
    restart: unless-stopped