services:
  proxy:
    container_name: proxy-nginx
    build:
      context: server
      dockerfile: Dockerfile.nginx
    image: proxy-nginx
    ports:
     - "8443:443"
     - "8080:80"
    networks: 
      - app_network
    volumes:
      - ./server/certs/:/certs
      - ./front:/var/www/static
    restart: unless-stopped