services:
  proxy:
    container_name: proxy-waf
    build:
      context: server
      dockerfile: Dockerfile.waf
    image: proxy-waf
    ports:
     - "443:443"
     - "80:80"
    networks: 
      - app_network
    volumes:
      - ./server/certs/:/certs
      - ./front:/var/www/static
    restart: unless-stopped
    # depends_on:
    #  logstash01:
    #    condition: service_healthy