services:
  tdjango:
    container_name: ${APP_NAME_2}
    build:
      context: apps/django_db_dev/django/
      dockerfile: Dockerfile.dev
    image: ${APP_NAME_2}_image
    env_file:
      - apps/django_db_dev/app.env.example
    volumes:
      - tsource_code:/app
      - ./logs:/logs
    networks:
      - app_network
    restart: unless-stopped
    entrypoint: ["python", "/app/manage.py", "runserver", "0.0.0.0:${APP_PORT_2}"]

  tpostgres:
    container_name: ${DB_NAME_2}
    build: apps/django_db_dev/postgres/
    image: ${DB_NAME_2}_image
    env_file:
      - apps/django_db_dev/app.env.example
    volumes:
      - tpgdata:${PGDATA}
      - ./logs:/logs
    networks: 
      - app_network
    restart: unless-stopped

volumes:
  tsource_code:
    name: ${APP_VOLUME_2}
    driver: local
    driver_opts:
      type: none
      device: apps/django_db_dev/django/src
      o: bind

  tpgdata:
    name: ${DB_VOLUME_2}
    driver: local
