services:
  chat:
    container_name: ${CHAT}
    build:
      context: apps/${CHAT}/django/
      dockerfile: Dockerfile.dev
    image: ${CHAT}_image
    env_file:
      - env.example/${CHAT}-common.env.example
    environment:
      - TZ=${TZ}
    volumes:
      - ${CHAT}_volume:/app
    networks:
      - app_network
    ports:
      - "8000:8000"
    restart: unless-stopped
      # logstash01:
      #  condition: service_healthy
    depends_on:
      chat-db:
       condition: service_healthy
    # stdin_open: true 
    # tty: true
    init: true
    entrypoint: ["bash", "/conf/init.sh"]

  chat-db:
    container_name: ${CHAT}-db
    build: apps/${CHAT}/postgres/
    image: ${CHAT}-db_image
    env_file:
      - env.example/${CHAT}-common.env.example
      - env.example/${CHAT}-db.env.example
    volumes:
      - ${CHAT}-db_volume:${PGDATA}
    networks: 
      - app_network
    restart: unless-stopped
    healthcheck:
      test: "pg_isready -U $$DB_USER -d $$DJ_DB_NAME || exit 1"
      retries: 3
      timeout: 5s
      interval: 600s
      start_period: 30s
      start_interval: 10s

  chat-redis:
    container_name: ${CHAT}-redis
    image: redis:7.2.4-alpine
    networks: 
      - app_network
    restart: unless-stopped

volumes:
  chat_volume:
    name: ${CHAT}
    driver: local
    driver_opts:
      type: none
      device: apps/${CHAT}/django/src
      o: bind

  chat-db_volume:
    name: ${CHAT}-db
    driver: local
