services:
  game:
    container_name: game
    build:
      context: apps/game/
      dockerfile: Dockerfile.dev
    image: game_image_dev
    environment:
      - TZ=${TZ}
    env_file:
      - conf/game.env
    volumes:
      - game_volume:/app
    networks:
      - app_network
      - game_network
    restart: unless-stopped
    depends_on:
      - game-redis

  game-redis:
    container_name: game-redis
    depends_on:
     data_views:
       condition: service_healthy
    image: redis:7.2.4-alpine
    networks: 
      - game_network
    restart: unless-stopped

networks:
  game_network:
    driver: bridge

volumes:
  game_volume:
    name: game_volume
    driver: local
    driver_opts:
      type: none
      device: apps/game/src
      o: bind
      