version: '3.9'


services:
  vault:
    container_name: vault
    build: context/
    image: my_vault
    env_file:
      - env.vault
    ports: 
      - "8200:8200"
    volumes:
      - ./data:/vault/file
      - ./logs:/vault/logs
    cap_add:
      - IPC_LOCK
    networks:
      - vault_network
    command: vault server -config=/vault/config/conf.json
    # command: /usr/bin/dumb-init /bin/sh docker-entrypoint/unseal.sh
    
  vault-init:
    container_name: vault-init
    build: init/
    image: my_init
    networks:
      - vault_network
    entrypoint: /usr/bin/dumb-init /bin/sh docker-entrypoint/unseal.sh
    depends_on:
      vault:
        condition: service_started
        restart: true

networks:
  vault_network:
    name: test_vault
    driver: bridge

# launch vault server -config
# launch unseal script