# Generated by Django 5.0.2 on 2024-04-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0004_usertoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='verification_key',
            new_name='unique_id',
        ),
    ]
