# Generated by Django 5.0.2 on 2024-04-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0007_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_picture',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
