# Generated by Django 5.0.2 on 2024-06-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0010_customuser_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='oauth_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
