# Generated by Django 5.0.2 on 2024-02-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtable',
            name='title',
        ),
        migrations.AddField(
            model_name='testtable',
            name='price',
            field=models.IntegerField(default=5),
        ),
    ]
