# Generated by Django 5.0.2 on 2024-02-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_testtable_title_testtable_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testTable',
        ),
    ]
