# Generated by Django 5.0.2 on 2024-02-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='emailToken',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
