# Generated by Django 5.0.2 on 2024-05-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0003_customuser_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_one', models.CharField(max_length=50)),
                ('user_one_score', models.IntegerField(blank=True)),
                ('user_one_powerups', models.IntegerField(blank=True)),
                ('user_two', models.CharField(blank=True, max_length=50)),
                ('user_two_score', models.IntegerField(blank=True)),
                ('user_two_powerups', models.IntegerField(blank=True)),
            ],
        ),
    ]
