# Generated by Django 5.0.2 on 2024-05-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0004_matchresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresults',
            name='user_one_powerups',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matchresults',
            name='user_one_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matchresults',
            name='user_two',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='matchresults',
            name='user_two_powerups',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matchresults',
            name='user_two_score',
            field=models.IntegerField(),
        ),
    ]
