# Generated by Django 5.0.2 on 2024-05-21 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0007_matchresults_match_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresults',
            name='user_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
    ]
