# Generated by Django 5.0.2 on 2024-05-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0009_alter_matchresults_user_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresults',
            name='user_one',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matchresults',
            name='user_two',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
