# Generated by Django 5.0.2 on 2024-05-23 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0016_alter_matchresults_user_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresults',
            name='user_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
