# Generated by Django 5.0.2 on 2024-05-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0018_alter_matchresults_user_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresults',
            name='user_two',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
