# Generated by Django 5.0.2 on 2024-05-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0020_matchresults_user_one_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchresults',
            old_name='user_one',
            new_name='user_one_id',
        ),
        migrations.RenameField(
            model_name='matchresults',
            old_name='user_two',
            new_name='user_two_id',
        ),
    ]
