# Generated by Django 5.0.2 on 2024-05-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0021_rename_user_one_matchresults_user_one_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchresults',
            old_name='user_one_id',
            new_name='user_one',
        ),
        migrations.RenameField(
            model_name='matchresults',
            old_name='user_two_id',
            new_name='user_two',
        ),
    ]
