# Generated by Django 5.0.2 on 2024-05-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0023_alter_matchresults_user_one_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchresults',
            old_name='user_two',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='matchresults',
            old_name='user_two_name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='matchresults',
            old_name='user_two_powerups',
            new_name='client_powerups',
        ),
        migrations.RenameField(
            model_name='matchresults',
            old_name='user_two_score',
            new_name='client_score',
        ),
        migrations.RenameField(
            model_name='matchresults',
            old_name='user_one',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='matchresults',
            old_name='user_one_name',
            new_name='host_name',
        ),
        migrations.RenameField(
            model_name='matchresults',
            old_name='user_one_powerups',
            new_name='host_powerups',
        ),
        migrations.RenameField(
            model_name='matchresults',
            old_name='user_one_score',
            new_name='host_score',
        ),
    ]
