version: '3.9'

services:
  django:
    container_name: ${APP_NAME}
    build:
      context: django/
      args: 
        PORT: ${PORT}
    image: ${APP_NAME}_image:${VERSION}
    environment:
      APP_NAME: ${APP_NAME}
      HOST: ${HOST}
      PORT: ${PORT}
    volumes:
    - app_data:/app
    ports:
    - "${PORT}:${PORT}"
    restart: unless-stopped
    stdin_open: true 
    tty: true

volumes:
  app_data:
    name: ${APP_VOLUME} 
    driver: local
    driver_opts:
      type: none
      device: django/src/
      o: bind

