version: '3.9'

services:
  django:
    container_name: ${APP_NAME}
    build:
      context: django/
      dockerfile: Dockerfile
    image: ${APP_NAME}_dev_image
    environment:
      APP_NAME: ${APP_NAME}
      PORT: ${PORT}
    volumes:
    - source_code:/app
    ports:
    - "${PORT}:${PORT}"
    restart: unless-stopped
    stdin_open: true 
    tty: true

volumes:
  source_code:
    name: ${APP_VOLUME} 
    driver: local
    driver_opts:
      type: none
      device: django/src/
      o: bind

