#image officiel de python, base sur alpine pour une taille minuscule
FROM python:3.12-alpine3.19

ENV PYTHONUNBUFFERED 1

COPY src/ /app
COPY conf/ /conf/
# RUN apk add python3 py3-pip python3-dev musl-dev gcc libffi-dev openssl-dev make libc-dev bash linux-headers

RUN pip install -r /conf/requirements.txt 

WORKDIR /app

EXPOSE ${PORT}

ENTRYPOINT ["sh", "/conf/init.sh"]
