# image officielle python : python version : 3.12, base sur debian bookworm, slim pour petite image
FROM python:3.12-slim-bookworm

# update and install utilies
RUN apt update -y \
	&& apt install -y curl git vim \
	build-essential python3-dev libpq-dev \
	postgresql-client-15 

RUN bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"

# ensure python output send straight to term and not buffered
ENV PYTHONUNBUFFERED 1

# create directory for docker volume where app will be
RUN mkdir /app /logs
WORKDIR /app

# install django requirements
COPY conf/ /conf/

RUN pip install -r /conf/requirements.txt 

# setup alias 
RUN echo >> /root/.bashrc \
	alias init="\"django-admin startproject \${APP_NAME} /app && echo django project created! || echo failed to create django project\"\n"\
	alias mkmig="\"python /app/manage.py makemigrations\"\n" \
	alias mig="\"python /app/manage.py migrate\"\n" \
	alias shell="\"python /app/manage.py shell\"\n" \
	alias viz="\"python /app/manage.py djangoviz\"\n" \
	alias run="\"python /app/manage.py runserver 0.0.0.0:8000\"\n" \
	alias help="\"echo init: start django project\necho mig: migrate\n echo run: launch django testserver\n echo conf: print app info\necho try to 'type [alias]' for exact command\"\n"

EXPOSE ${PORT}

